climber units
1757WestwoodRobotics/2022-RapidReact pull request #104
Opened 2022-04-06 23:39 UTC by LandonBayer

2022-04-06 23:49 UTC, lmaxwell24 submitted a review, later dismissed

2022-04-06 23:56 UTC, caloisio requested changes

2022-04-06 23:56 UTC, caloisio commented on constants.py
> +kClimberRetractionWaitTime = 2  # seconds
Should be of the form
```python
kClimberRetractionWaitTime = 2
"""seconds"""
```
so that it shows up nicely in hints

2022-04-06 23:56 UTC, caloisio commented on constants.py
>  kClimberMiddleRungCapturePosition = 344502
Comment these individually (also for proper hints)

2022-04-07 00:03 UTC, caloisio submitted a review, later dismissed
Good enough for now. Technically the hinting tools like it better if there is a newline separating each element but :man_shrugging: 
(e.g.
```python
kClimberRetractionWaitTime = 2
"""seconds"""

kClimberMiddleRungCapturePosition = 344502
"""encoder ticks"""
```
)

2022-04-07 00:12 UTC, caloisio approved these changes
:+1: :+1: :+1: :+1: :+1:

2022-04-07 00:13 UTC, lmaxwell24 approved these changes

2022-04-07 00:13 UTC, merged