Replace simulated encoder with encoder of ctre simulated falcon
1757WestwoodRobotics/2022-RapidReact pull request #80
Opened 2022-03-25 23:30 UTC by caloisio

2022-03-26 12:00 UTC, LandonBayer submitted a review, later dismissed

2022-03-28 22:04 UTC, lmaxwell24 requested changes

2022-03-28 22:04 UTC, lmaxwell24 commented on util/helpfulIO.py
> +                        / 50  # 50 updates per second
do we have the constant for this?

2022-03-28 22:18 UTC, lmaxwell24 approved these changes

2022-03-28 22:44 UTC, LandonBayer commented
Assuming this works fine, which it should; we're good

2022-03-28 22:45 UTC, LandonBayer approved these changes

2022-03-29 01:19 UTC, closed without merging